---
title: "#python では標準ライブラリと同名のファイルは作ってはいけない ( わけではないかもしれないが、謎の import エラーが出る場合の"
emoji: "🖥"
type: "idea"
topics: ["Python"]
published: true
---

# ./test.py

```
from datetime import datetime 
```

# ./datetime.py

空ファイル

# execute
```
$ python3 ./test.py
Traceback (most recent call last):
  File "./test.py", line 1, in <module>
    from datetime import datetime
ImportError: cannot import name 'datetime' from 'datetime' (/Users/yumainaura/.ghq/github.com/YumaInaura/YumaInaura/python/datetime.py)
```

# Error reading

どこからライブラリを読み込もうとしているか見てみよう

```
(/Users/yumainaura/.ghq/github.com/YumaInaura/YumaInaura/python/datetime.py)
```

# 解決

独自ライブラリファイル `./datetime.py` は別名に変更する

# 標準ライブラリから読み込む方法

未調査

# Original by Github issue

https://github.com/YumaInaura/YumaInaura/issues/1067








<!-- Update From Qiita API -->

# チャットメンバー募集


何か質問、悩み事、相談などあればLINEオープンチャットもご利用ください。

https://line.me/ti/g2/eEPltQ6Tzh3pYAZV8JXKZqc7PJ6L0rpm573dcQ





# Twitter


https://twitter.com/YumaInaura


<!-- Update From Qiita API -->


